# Compiler/Flag Variables
CXX=g++
CXXFLAGS = -std=c++11
CXXFLAGS += -g
CXXFLAGS += -Wall
CXXFLAGS += -pedantic
CXXFLAGS += -Wextra
CXXFLAGS += -Weffc++


# all Variables

INTERFACEOBJECTS = interface.o
INTERFACESRCS = interface.cpp
INTERFACEHEADERS = interface.hpp

all:

test: 

clean:
	-rm ${VARIABLEOBJECTS} 