# Compiler/Flag Variables
CXX=g++
CXXFLAGS = -std=c++11
CXXFLAGS += -g
CXXFLAGS += -Wall
CXXFLAGS += -pedantic
CXXFLAGS += -Wextra
CXXFLAGS += -Weffc++


# all Variables

VARIABLEOBJECTS = v1.o v2.o
VARIABLESRCS = v1.cpp v2.cpp
VARIABLEHEADERS = v1.hpp v2.hpp

all:

test: 

clean:
	-rm ${VARIABLEOBJECTS} 